bankproject/bankapp/urls.py
from . import views
from django.urls import path
app_name="bankapp"
urlpatterns = [

    path('',views.demo,name='demo'),
    path('student-form/', views.student_form, name='student_form'),
    path('odercom/', views.odercom, name='odercom'),

]

bankproject/bankproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bankapp.urls')),
    path('credentials/',include('credentials.urls'))
]



if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

bankproject/credentials/urls.py
from . import views
from django.urls import path
app_name="credentials"

urlpatterns = [

    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),


]

bankproject/bankapp/models.py
from django.db import models

# Create your models here.

bankproject/credentials/models.py
from django.db import models

# Create your models here.

bankproject/bankapp/views.py
# views.py
from django.contrib import messages

from django.shortcuts import render

# Create your views here.
def demo(request):

    return render(request,'index.html')



def student_form(request, ):
    return render(request, 'form1.html')


def odercom(request):

    if request.method == 'POST':
        firstname = request.POST['first_name']
        lastname = request.POST['last_name']
        birthday = request.POST['birthday']
        age = request.POST['age']
        # gender = request.POST['gender']
        email = request.POST['email']
        phone = request.POST['phone']
        address = request.POST['address']
        purpose = request.POST['purpose']

        if firstname == "" or lastname == "" or birthday == "" or age == "" \
                or email == "" or phone == "" or address == '' or purpose == "":
            print("Please fill the fields")
            messages.info(request, 'Please fill all the fields')
            return render(request,'form1.html')
        else:
            return render(request, 'odercom.html')

    return render(request, 'odercom.html')

bankproject/credentials/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
def login(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None :
            auth.login(request,user)
            return render(request,'button.html')
        else:
            messages.info(request,'invalid crendentials')
            return redirect('login')
    return render(request,('login.html'))
def register(request):
    if request.method=='POST':
        username=request.POST['username']
        # firstname = request.POST['first_name']
        # lastname = request.POST['last_name']
        # email = request.POST['email']
        password = request.POST['password']
        cpassword = request.POST['password1']
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,"Username already taken")
                return render(request,('register.html'))
            # elif User.objects.filter(email=email).exists():
            #     messages.info(request,"email already taken")
            #     return redirect('register')
            else:
                user=User.objects.create_user(username=username,password=password)
                # print("user registered")
                user.save();
                return render(request,('login.html'))

        else:
            messages.info(request,'password not matching')
            return render(request,('register.html'))
        return redirect('/')

    return render(request,('register.html'))
def logout(request):
    auth.logout(request)
    return redirect('/')

bankproject/templates/button.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>form button</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/button.css' %}">

</head>
<body>


<!-- Flex Container -->
<div id="container">
    <div class="button" id="button-5">
    <div id="translate"></div>
    <a href="{% url 'bankapp:student_form' %}">Open Form!</a>
  </div>


  <!-- End Container -->
</div>

</body>
</html>

bankproject/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Form</title>
    <script>
        function getCities() {
            var country = document.getElementById('country').value;
            var cities = document.getElementById('city');
            cities.options.length = 0;
            switch (country) {
                case 'computer science':
                    cities.options.add(new Option('CS engineering', 'CS engineering'));
                    cities.options.add(new Option('BCA', 'BCA'));

                    break;

                case 'Science':
                    cities.options.add(new Option('Engineering', ' Engineering'));
                    cities.options.add(new Option('Bsc', 'Bsc'));

                    break;

                case 'Commerce':
                    cities.options.add(new Option('Bcom', 'Bcom'));
                    cities.options.add(new Option('Bba', 'Bba'));

                    break;
                case 'IT':
                    cities.options.add(new Option('Cyber Security', ' Cyber Security'));
                    cities.options.add(new Option('Animation', 'Animation'));

                    break;

                case 'Humanities':
                    cities.options.add(new Option('BA History', ' BA History'));
                    cities.options.add(new Option('MA History', 'MA History'));

                    break;






                default:
                    break;
            }
        }
    </script>
</head>
<body>
<form action="{% url 'formapp:odercom' %}" method="post">
	{% csrf_token %}
   <label for="2name">Name:</label><br>
  <input type="text" id="2name" name="Name"><br>
  <label for="1name">DOB:</label><br>
  <input type="date" id="1name" name="DOB"><br>
    <label for="age">Age:</label><br>
  <input type="number" id="age" name="age"><br>
  <label for="phnumber">Phone:</label><br>
  <input type="number" id="phnumber" name="phnumber"><br>
     <input type="radio" id="gender" name="gender" value="Male">
  <label for="gender">Male</label>
  <input type="radio" id="gender1" name="gender" value="Female">
  <label for="gender1">Female</label><br>
    <label for="mail">Email:</label><br>
  <input type="email" id="mail" name="mail"><br>
    <label for="address">Address:</label><br>
    <textarea id="address" name="address" rows="4" cols="20"></textarea><br>


    <label for="country">Dept:</label>
    <select id="country" onchange="getCities()">
        <option value="">Select Dept </option>
        <option value="computer science">Computer science</option>
        <option value="Science">Science</option>
        <option value="Commerce">Commerce</option>
        <option value="IT">IT</option>
        <option value="Humanities">Humanities</option>


    </select>
    <br>
    <br>
    <label for="city">Courses:</label>
    <select id="city">
    </select>
    <br>
    <br>
    <label for="purpose">Purpose:</label>

<select name="purpose" id="purpose">
    <option value="">select</option>
  <option value="ForEnquiry">ForEnquiry</option>
  <option value="PlaceOrder">Place order</option>
  <option value="Return">Return</option>
</select>
    <br>
<label>Materials provide:</label><br>
    <input type="checkbox" id="matrls" name="matrl1" value="notebook">
  <label for="matrls"> NoteBook</label><br>
  <input type="checkbox" id="matrls1" name="matrl2" value="Pen">
  <label for="matrls1"> Pen</label><br>
  <input type="checkbox" id="matrsl2" name="matrl2" value="ExamPaper">
  <label for="matrsl2">ExamPaper</label><br><br>
  <input type="submit" value="Submit">

</form>
<a href="{% url 'credentials:logout' %}"><button>Logout</button></a>
</body>
</html>

bankproject/templates/form1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <script>
        function getCities() {
            var country = document.getElementById('country').value;
            var cities = document.getElementById('city');
            cities.options.length = 0;
            switch (country) {
                case 'Ernakulam':
                    cities.options.add(new Option('Aluva', 'Aluva'));
                    cities.options.add(new Option('Edapally', 'Edapally'));

                    break;

                case 'Idukki':
                    cities.options.add(new Option('Adimaly', ' Adimaly'));
                    cities.options.add(new Option('Kattappana', 'Kattappana'));

                    break;

                case 'Kottayam':
                    cities.options.add(new Option('Kanjirapally', 'Kanjirapally'));
                    cities.options.add(new Option('Pala', 'Pala'));

                    break;
                case 'Pathanamthitta':
                    cities.options.add(new Option('Adoor', ' Adoor'));
                    cities.options.add(new Option('Ranni', 'Ranni'));

                    break;

                case 'Thiruvananthapuram':
                    cities.options.add(new Option('Kanakakkunnu', 'Kanakakkunnu'));
                    cities.options.add(new Option('Kilimanoor', 'Kilimanoor'));

                    break;






                default:
                    break;
            }
        }
    </script>
<!--
    <-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Form page</title>

    <!-- Icons font CSS-->
    <link href="{% static 'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" media="all">
</head>

<body>
    <div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
        <div class="wrapper wrapper--w680">
            <div class="card card-4">
                <div class="card-body">
                    <h2 class="title">Fill this Form</h2>
                    <form  action="{% url 'bankapp:odercom' %}" method="POST" >
                        {% csrf_token %}
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label  class="label">first name</label>
                                    <input class="input--style-4" type="text" name="first_name">
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">last name</label>
                                    <input class="input--style-4" type="text" name="last_name">
                                </div>
                            </div>
                        </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Birthday</label>
                                    <div class="input-group-icon">
                                        <input class="input--style-4 js-datepicker" type="text" name="birthday">
                                        <i class="zmdi zmdi-calendar-note input-icon js-btn-calendar"></i>
                                    </div>
                                </div>
                            </div>

                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Age</label>
                                    <input class="input--style-4" type="number" name="age">
                                </div>
                                </div>
                                <br>
                                <div class="input-group">
                                    <label class="label">Gender</label>
                                    <div class="p-t-10">
                                        <label class="radio-container m-r-45">Male
                                            <input type="radio" checked="checked" name="gender">
                                            <span class="checkmark"></span>
                                        </label>
                                        <label class="radio-container m-r-45">Female
                                            <input type="radio" name="gender">
                                            <span class="checkmark"></span>
                                        </label>
                                        <label class="radio-container">Others
                                            <input type="radio" name="gender">
                                            <span class="checkmark"></span>
                                        </label>
                                    </div>
                                </div>

                        </div>

                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Email</label>
                                    <input class="input--style-4" type="email" name="email">
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Phone Number</label>
                                    <input class="input--style-4" type="number" name="phone">
                                </div>
                            </div>
                        </div>
                        <div class="row row-space">
                        <label class="label">Address:</label><br>
                        <textarea class="input--style-4" id="address" name="address" rows="4" cols="20"></textarea><br>
                        </div>

                        <div class="input-group">
                            <label class="label" for="country">District:</label>
                            <div class="rs-select2 js-select-simple select&#45;&#45;no-search">
                            <select  id="country" onchange="getCities()">
                        <option  value="">Select Dist </option>
                        <option  value="Ernakulam">Ernakulam</option>
                        <option value="Idukki">Idukki</option>
                         <option value="Kottayam">Kottayam</option>
                        <option value="Pathanamthitta">Pathanamthitta</option>
                        <option value="Thiruvananthapuram">Thiruvananthapuram</option>

                        </select>
                                <div class="select-dropdown"></div>
                            </div>

                             <br>
                        <label class="label" for="city">Branch:</label>
                            <div class="rs-select2 js-select-simple select&#45;&#45;no-search">
                        <select id="city">
                        </select>
                                <div class="select-dropdown"></div>
                            </div>
                        </div>
                        <br>

                        <label class="label" for="purpose">Account type:</label>
<!--                            <div class="rs-select2 js-select-simple select&#45;&#45;no-search">-->
                        <select name="purpose" id="purpose">
                            <option class="label" value="">select</option>
                            <option class="label" value="ForEnquiry">Savings Account</option>
                        <option class="label" value="PlaceOrder">Current Account</option>

                        </select>
<!--                                <div class="select-dropdown"></div>-->
<!--                            </div>-->
                            <br>
                            <br>

                        <label class="label">Materials provide:</label>

                        <input type="checkbox" id="matrls" name="matrl1" value="Debit card">
                        <label for="matrls"> Debit card</label><br>
                        <input type="checkbox" id="matrls1" name="matrl2" value="Credit card">
                        <label for="matrls1">  Credit card</label><br>
                        <input type="checkbox" id="matrsl2" name="matrl2" value="cheque book">
                        <label for="matrsl2">cheque book</label><br><br>


                        <div class="p-t-15">
                            <button  class="btn btn--radius-2 btn--blue" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
            {% for msg in messages %}
    <h2>{{msg}}</h2>
    {% endfor %}
        </div>
    </div>

    <!-- Jquery JS-->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <!-- Vendor JS-->
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/daterangepicker.js' %}"></script>

    <!-- Main JS-->
    <script src="{% static 'js/global.js' %}"></script>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
<!-- end document-->

bankproject/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <title>Welcome</title>
 <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'css/fontawesome1.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-grad-school.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'css/lightbox.css' %}">

<!--<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />-->
<!--<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />-->

</head>
<body>

   <header class="main-header clearfix" role="header">
    <div class="logo">
      <a href="#"><em>National</em> Bank</a>
    </div>
    <a href="#menu" class="menu-link"><i class="fa fa-bars"></i></a>
    <nav id="menu" class="main-nav" role="navigation">
      <ul class="main-menu">
        <li><a href="#section1">Home</a></li>
        <li class="has-submenu"><a href="#">Branches</a>
          <ul class="sub-menu">
            <li><a href="https://en.wikipedia.org/wiki/Ernakulam_district">Ernakulam</a></li>
            <li><a href="https://en.wikipedia.org/wiki/Idukki_district">Idukki</a></li>
            <li><a href="https://en.wikipedia.org/wiki/Kottayam_district">Kottayam</a></li>
            <li><a href="https://en.wikipedia.org/wiki/Pathanamthitta_district">Pathanamthitta</a></li>
            <li><a href="https://en.wikipedia.org/wiki/Thiruvananthapuram_district">Thiruvananthapuram</a></li>
          </ul>
        </li>
<!--        <li><a  href="#section4">Login</a></li>-->
        <li><a href="{% url 'credentials:login' %}" type="button" class="btn btn-success">Login</a></li>
        <!-- <li><a href="#section5">Video</a></li> -->
        <li><a href="{% url 'credentials:register' %}" type="button" class="btn btn-danger">Register</a></li>

<!--        <li><a href="#section6">Register</a></li>-->
<!--        <li><a href="https://templatemo.com" class="external">External</a></li>-->
      </ul>
    </nav>
  </header>
   <!-- ***** Main Banner Area Start ***** -->
  <section class="section main-banner" id="top" data-section="section1">
      <video autoplay muted loop id="bg-video">
          <source src="{% static 'images/course-video.mp4' %}" type="video/mp4" />
      </video>

      <div class="video-overlay header-text">
          <div class="caption">
              <h6>National Bank of India</h6>
              <h2><em>BANKING</em> SOLUTIONS</h2>
              <div class="main-button">
                  <div class="scroll-to-section"><a href="#section2">Discover more</a></div>
              </div>
          </div>
      </div>
  </section>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p><i class="fa fa-copyright"></i> Copyright 2020 by national bank

          </p>
        </div>
      </div>
    </div>
  </footer>
<script>
        //according to loftblog tut
        $('.nav li:first').addClass('active');

        var showSection = function showSection(section, isAnimate) {
          var
          direction = section.replace(/#/, ''),
          reqSection = $('.section').filter('[data-section="' + direction + '"]'),
          reqSectionPos = reqSection.offset().top - 0;

          if (isAnimate) {
            $('body, html').animate({
              scrollTop: reqSectionPos },
            800);
          } else {
            $('body, html').scrollTop(reqSectionPos);
          }

        };

        var checkSection = function checkSection() {
          $('.section').each(function () {
            var
            $this = $(this),
            topEdge = $this.offset().top - 80,
            bottomEdge = topEdge + $this.height(),
            wScroll = $(window).scrollTop();
            if (topEdge < wScroll && bottomEdge > wScroll) {
              var
              currentId = $this.data('section'),
              reqLink = $('a').filter('[href*=\\#' + currentId + ']');
              reqLink.closest('li').addClass('active').
              siblings().removeClass('active');
            }
          });
        };

        $('.main-menu, .scroll-to-section').on('click', 'a', function (e) {
          if($(e.target).hasClass('external')) {
            return;
          }
          e.preventDefault();
          $('#menu').removeClass('active');
          showSection($(this).attr('href'), true);
        });

        $(window).scroll(function () {
          checkSection();
        });
    </script>

</body>
</html>

bankproject/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <style>
        @import url(https://fonts.googleapis.com/css?family=Roboto:300);

.login-page {
  width: 360px;
  padding: 8% 0 0;
  margin: auto;
}
.form {
  position: relative;
  z-index: 1;
  background: #FFFFFF;
  max-width: 360px;
  margin: 0 auto 100px;
  padding: 45px;
  text-align: center;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}
.form input {
  font-family: "Roboto", sans-serif;
  outline: 0;
  background: #f2f2f2;
  width: 100%;
  border: 0;
  margin: 0 0 15px;
  padding: 15px;
  box-sizing: border-box;
  font-size: 14px;
}
.form button {
  font-family: "Roboto", sans-serif;
  text-transform: uppercase;
  outline: 0;
  background: #4CAF50;
  width: 100%;
  border: 0;
  padding: 15px;
  color: #FFFFFF;
  font-size: 14px;
  -webkit-transition: all 0.3 ease;
  transition: all 0.3 ease;
  cursor: pointer;
}
.form button:hover,.form button:active,.form button:focus {
  background: #43A047;
}
.form .message {
  margin: 15px 0 0;
  color: #b3b3b3;
  font-size: 12px;
}
.form .message a {
  color: #4CAF50;
  text-decoration: none;
}
.form .register-form {
  display: none;
}
.container {
  position: relative;
  z-index: 1;
  max-width: 300px;
  margin: 0 auto;
}
.container:before, .container:after {
  content: "";
  display: block;
  clear: both;
}
.container .info {
  margin: 50px auto;
  text-align: center;
}
.container .info h1 {
  margin: 0 0 15px;
  padding: 0;
  font-size: 36px;
  font-weight: 300;
  color: #1a1a1a;
}
.container .info span {
  color: #4d4d4d;
  font-size: 12px;
}
.container .info span a {
  color: #000000;
  text-decoration: none;
}
.container .info span .fa {
  color: #EF3B3A;
}
body {
  background: #76b852; /* fallback for old browsers */
  background: rgb(141,194,111);
  background: linear-gradient(90deg, rgba(141,194,111,1) 0%, rgba(118,184,82,1) 50%);
  font-family: "Roboto", sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
    </style>
</head>
<body>
<div class="login-page">
  <div class="form">
    <form class="login-form" action="login" method="post">
        {% csrf_token %}
      <input type="text" name="username" placeholder="username"/>
      <input type="password" name="password" placeholder="password"/>
      <button>login</button>
      <p class="message">Not registered? <a href="register">Create an account</a></p>
    </form>
  </div>
</div>
</body>
{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}
</html>

bankproject/templates/odercom.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Oder Confirmation</title>
</head>
<body>
<h1>Your Application accepted</h1>
<h3>Go back to home!</h3>
<a href="{% url 'credentials:logout' %}">Home</a>
</body>
</html>

bankproject/templates/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>SignUp Form</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Custom Theme files -->

<link href="{% static 'css/register.css' %}" rel="stylesheet" type="text/css" media="all" />
<!-- //Custom Theme files -->
<!-- web font -->
<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
<!-- //web font -->
</head>
    <body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1> SignUp Form</h1>
		<div class="main-agileinfo">
			<div class="agileits-top">
				<form action="register" method="post">
                    {% csrf_token %}
					<input class="text" type="text" name="username" placeholder="Username" required="">
					<input class="text w3lpass" type="password" name="password" placeholder="Password"  required="">
					<input class="text w3lpass" type="password" name="password1" placeholder="Confirm Password" required="">
					<div class="wthree-text">
						<label class="anim">
							<input type="checkbox" class="checkbox" required="">
							<span>I Agree To The Terms & Conditions</span>
						</label>
						<div class="clear"> </div>
					</div>
					<input type="submit" value="SIGNUP">
				</form>
				<p>Don't have an Account? <a href="login"> Login Now!</a></p>
			</div>
		</div>
    </div>
        {% for msg in messages %}
    <h2>{{msg}}</h2>
    {% endfor %}

    </body>
</html>